In [2]:
# 필요패키지 import
import time
import numpy as np
import pandas as pd

import urllib
import json
import requests
from bs4 import BeautifulSoup

In [166]:
df = pd.DataFrame(columns=['date', 'price', 'delta', 'volume'])
date_list = []
price_list = []
# price_list_prime = []
delta_list = []
volume_list = []
n = 663
kosdak_delta = []
for i in range(n + 1):
    
    seed = np.random.randint(100)
    np.random.seed(seed)
    a = np.random.randint(5) # 난수가 생성 생성된 난수에 따라서 요청하는 시간 딜레이
    time.sleep(a)
    
    url = f'https://finance.naver.com/sise/sise_index_day.nhn?code=KOSPI&page={i}'
    header = {
        'referer' : f'https://finance.naver.com/sise/sise_index_day.nhn?code=KOSPI&page={i}',
        'user-agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36'
    }
    response = requests.get(url, headers = header)
    
    if response.status_code == requests.codes.ok:
        print(i," 번째 접속성공")
    
    html = BeautifulSoup(response.text, 'html.parser')

    for j in html.select('td.date'): # 날짜 data crawling
        date_list.append(j.text)

    for j in html.select('td.number_1')[0::4]: # 종가 data crawling
        price_list.append(j.text)

    for j in html.select('td.number_1')[4::4]: # 전일 종가 data crawling
        price_list_prime.append(j.text)
    
    for j in html.select('td.number_1')[2::4]: # 거래량(천 주) data crwaling
        volume_list.append(j.text)

for i in range(len(price_list)):
    price_list[i] = float(price_list[i].replace(',',''))
    volume_list[i] = int(volume_list[i].replace(',',''))
df['price'] = price_list
df['volume'] = volume_list
df['date'] = date_list

for i in range(len(df) - 1):
    delta_list.append(round(price_list[i] - price_list[i+1], 2))
delta_list.append(0)
df['delta'] = delta_list


kospi = df[0:len(df) - 1]
kospi.to_csv('kospi_data.csv')

0  번째 접속성공
1  번째 접속성공
2  번째 접속성공
3  번째 접속성공
4  번째 접속성공
5  번째 접속성공
6  번째 접속성공
7  번째 접속성공
8  번째 접속성공
9  번째 접속성공
10  번째 접속성공
11  번째 접속성공
12  번째 접속성공
13  번째 접속성공
14  번째 접속성공
15  번째 접속성공
16  번째 접속성공
17  번째 접속성공
18  번째 접속성공
19  번째 접속성공
20  번째 접속성공
21  번째 접속성공
22  번째 접속성공
23  번째 접속성공
24  번째 접속성공
25  번째 접속성공
26  번째 접속성공
27  번째 접속성공
28  번째 접속성공
29  번째 접속성공
30  번째 접속성공
31  번째 접속성공
32  번째 접속성공
33  번째 접속성공
34  번째 접속성공
35  번째 접속성공
36  번째 접속성공
37  번째 접속성공
38  번째 접속성공
39  번째 접속성공
40  번째 접속성공
41  번째 접속성공
42  번째 접속성공
43  번째 접속성공
44  번째 접속성공
45  번째 접속성공
46  번째 접속성공
47  번째 접속성공
48  번째 접속성공
49  번째 접속성공
50  번째 접속성공
51  번째 접속성공
52  번째 접속성공
53  번째 접속성공
54  번째 접속성공
55  번째 접속성공
56  번째 접속성공
57  번째 접속성공
58  번째 접속성공
59  번째 접속성공
60  번째 접속성공
61  번째 접속성공
62  번째 접속성공
63  번째 접속성공
64  번째 접속성공
65  번째 접속성공
66  번째 접속성공
67  번째 접속성공
68  번째 접속성공
69  번째 접속성공
70  번째 접속성공
71  번째 접속성공
72  번째 접속성공
73  번째 접속성공
74  번째 접속성공
75  번째 접속성공
76  번째 접속성공
77  번째 접속성공
78  번째 접속성공
79  번째 접속성공
80  번째 접속성공
81  번째 접속성공
82  번째 접속성공
83  번째 접속성공
84  번째 접속성공
85  번째 접속성공
86  번째 접속성공
87  번째 접속성공
88  번째 접속성공
89  번째 접속성공
90  번째 접속성공
91  번째 접속성공
92  번째 접속성공
93  번째 접속성공
94  번째 접속성공
95  번째 접속성공
96  번째 접속성공
97  번째 접속성공
98  번째 접속성공
99  번째 접속성공
100  번째 접속성공
101  번째 접속성공
102  번째 접속성공
103  번째 접속성공
104  번째 접속성공
105  번째 접속성공
106  번째 접속성공
107  번째 접속성공
108  번째 접속성공
109  번째 접속성공
110  번째 접속성공
111  번째 접속성공
112  번째 접속성공
113  번째 접속성공
114  번째 접속성공
115  번째 접속성공
116  번째 접속성공
117  번째 접속성공
118  번째 접속성공
119  번째 접속성공
120  번째 접속성공
121  번째 접속성공
122  번째 접속성공
123  번째 접속성공
124  번째 접속성공
125  번째 접속성공
126  번째 접속성공
127  번째 접속성공
128  번째 접속성공
129  번째 접속성공
130  번째 접속성공
131  번째 접속성공
132  번째 접속성공
133  번째 접속성공
134  번째 접속성공
135  번째 접속성공
136  번째 접속성공
137  번째 접속성공
138  번째 접속성공
139  번째 접속성공
140  번째 접속성공
141  번째 접속성공
142  번째 접속성공
143  번째 접속성공
144  번째 접속성공
145  번째 접속성공
146  번째 접속성공
147  번째 접속성공
148  번째 접속성공
149  번째 접속성공
150  번째 접속성공
151  번째 접속성공
152  번째 접속성공
153  번째 접속성공
154  번째 접속성공
155  번째 접속성공
156  번째 접속성공
157  번째 접속성공
158  번째 접속성공
159  번째 접속성공
160  번째 접속성공
161  번째 접속성공
162  번째 접속성공
163  번째 접속성공
164  번째 접속성공
165  번째 접속성공
166  번째 접속성공
167  번째 접속성공
168  번째 접속성공
169  번째 접속성공
170  번째 접속성공
171  번째 접속성공
172  번째 접속성공
173  번째 접속성공
174  번째 접속성공
175  번째 접속성공
176  번째 접속성공
177  번째 접속성공
178  번째 접속성공
179  번째 접속성공
180  번째 접속성공
181  번째 접속성공
182  번째 접속성공
183  번째 접속성공
184  번째 접속성공
185  번째 접속성공
186  번째 접속성공
187  번째 접속성공
188  번째 접속성공
189  번째 접속성공
190  번째 접속성공
191  번째 접속성공
192  번째 접속성공
193  번째 접속성공
194  번째 접속성공
195  번째 접속성공
196  번째 접속성공
197  번째 접속성공
198  번째 접속성공
199  번째 접속성공
200  번째 접속성공
201  번째 접속성공
202  번째 접속성공
203  번째 접속성공
204  번째 접속성공
205  번째 접속성공
206  번째 접속성공
207  번째 접속성공
208  번째 접속성공
209  번째 접속성공
210  번째 접속성공
211  번째 접속성공
212  번째 접속성공
213  번째 접속성공
214  번째 접속성공
215  번째 접속성공
216  번째 접속성공
217  번째 접속성공
218  번째 접속성공
219  번째 접속성공
220  번째 접속성공
221  번째 접속성공
222  번째 접속성공
223  번째 접속성공
224  번째 접속성공
225  번째 접속성공
226  번째 접속성공
227  번째 접속성공
228  번째 접속성공
229  번째 접속성공
230  번째 접속성공
231  번째 접속성공
232  번째 접속성공
233  번째 접속성공
234  번째 접속성공
235  번째 접속성공
236  번째 접속성공
237  번째 접속성공
238  번째 접속성공
239  번째 접속성공
240  번째 접속성공
241  번째 접속성공
242  번째 접속성공
243  번째 접속성공
244  번째 접속성공
245  번째 접속성공
246  번째 접속성공
247  번째 접속성공
248  번째 접속성공
249  번째 접속성공
250  번째 접속성공
251  번째 접속성공
252  번째 접속성공
253  번째 접속성공
254  번째 접속성공
255  번째 접속성공
256  번째 접속성공
257  번째 접속성공
258  번째 접속성공
259  번째 접속성공
260  번째 접속성공
261  번째 접속성공
262  번째 접속성공
263  번째 접속성공
264  번째 접속성공
265  번째 접속성공
266  번째 접속성공
267  번째 접속성공
268  번째 접속성공
269  번째 접속성공
270  번째 접속성공
271  번째 접속성공
272  번째 접속성공
273  번째 접속성공
274  번째 접속성공
275  번째 접속성공
276  번째 접속성공
277  번째 접속성공
278  번째 접속성공
279  번째 접속성공
280  번째 접속성공
281  번째 접속성공
282  번째 접속성공
283  번째 접속성공
284  번째 접속성공
285  번째 접속성공
286  번째 접속성공
287  번째 접속성공
288  번째 접속성공
289  번째 접속성공
290  번째 접속성공
291  번째 접속성공
292  번째 접속성공
293  번째 접속성공
294  번째 접속성공
295  번째 접속성공
296  번째 접속성공
297  번째 접속성공
298  번째 접속성공
299  번째 접속성공
300  번째 접속성공
301  번째 접속성공
302  번째 접속성공
303  번째 접속성공
304  번째 접속성공
305  번째 접속성공
306  번째 접속성공
307  번째 접속성공
308  번째 접속성공
309  번째 접속성공
310  번째 접속성공
311  번째 접속성공
312  번째 접속성공
313  번째 접속성공
314  번째 접속성공
315  번째 접속성공
316  번째 접속성공
317  번째 접속성공
318  번째 접속성공
319  번째 접속성공
320  번째 접속성공
321  번째 접속성공
322  번째 접속성공
323  번째 접속성공
324  번째 접속성공
325  번째 접속성공
326  번째 접속성공
327  번째 접속성공
328  번째 접속성공
329  번째 접속성공
330  번째 접속성공
331  번째 접속성공
332  번째 접속성공
333  번째 접속성공
334  번째 접속성공
335  번째 접속성공
336  번째 접속성공
337  번째 접속성공
338  번째 접속성공
339  번째 접속성공
340  번째 접속성공
341  번째 접속성공
342  번째 접속성공
343  번째 접속성공
344  번째 접속성공
345  번째 접속성공
346  번째 접속성공
347  번째 접속성공
348  번째 접속성공
349  번째 접속성공
350  번째 접속성공
351  번째 접속성공
352  번째 접속성공
353  번째 접속성공
354  번째 접속성공
355  번째 접속성공
356  번째 접속성공
357  번째 접속성공
358  번째 접속성공
359  번째 접속성공
360  번째 접속성공
361  번째 접속성공
362  번째 접속성공
363  번째 접속성공
364  번째 접속성공
365  번째 접속성공
366  번째 접속성공
367  번째 접속성공
368  번째 접속성공
369  번째 접속성공
370  번째 접속성공
371  번째 접속성공
372  번째 접속성공
373  번째 접속성공
374  번째 접속성공
375  번째 접속성공
376  번째 접속성공
377  번째 접속성공
378  번째 접속성공
379  번째 접속성공
380  번째 접속성공
381  번째 접속성공
382  번째 접속성공
383  번째 접속성공
384  번째 접속성공
385  번째 접속성공
386  번째 접속성공
387  번째 접속성공
388  번째 접속성공
389  번째 접속성공
390  번째 접속성공
391  번째 접속성공
392  번째 접속성공
393  번째 접속성공
394  번째 접속성공
395  번째 접속성공
396  번째 접속성공
397  번째 접속성공
398  번째 접속성공
399  번째 접속성공
400  번째 접속성공
401  번째 접속성공
402  번째 접속성공
403  번째 접속성공
404  번째 접속성공
405  번째 접속성공
406  번째 접속성공
407  번째 접속성공
408  번째 접속성공
409  번째 접속성공
410  번째 접속성공
411  번째 접속성공
412  번째 접속성공
413  번째 접속성공
414  번째 접속성공
415  번째 접속성공
416  번째 접속성공
417  번째 접속성공
418  번째 접속성공
419  번째 접속성공
420  번째 접속성공
421  번째 접속성공
422  번째 접속성공
423  번째 접속성공
424  번째 접속성공
425  번째 접속성공
426  번째 접속성공
427  번째 접속성공
428  번째 접속성공
429  번째 접속성공
430  번째 접속성공
431  번째 접속성공
432  번째 접속성공
433  번째 접속성공
434  번째 접속성공
435  번째 접속성공
436  번째 접속성공
437  번째 접속성공
438  번째 접속성공
439  번째 접속성공
440  번째 접속성공
441  번째 접속성공
442  번째 접속성공
443  번째 접속성공
444  번째 접속성공
445  번째 접속성공
446  번째 접속성공
447  번째 접속성공
448  번째 접속성공
449  번째 접속성공
450  번째 접속성공
451  번째 접속성공
452  번째 접속성공
453  번째 접속성공
454  번째 접속성공
455  번째 접속성공
456  번째 접속성공
457  번째 접속성공
458  번째 접속성공
459  번째 접속성공
460  번째 접속성공
461  번째 접속성공
462  번째 접속성공
463  번째 접속성공
464  번째 접속성공
465  번째 접속성공
466  번째 접속성공
467  번째 접속성공
468  번째 접속성공
469  번째 접속성공
470  번째 접속성공
471  번째 접속성공
472  번째 접속성공
473  번째 접속성공
474  번째 접속성공
475  번째 접속성공
476  번째 접속성공
477  번째 접속성공
478  번째 접속성공
479  번째 접속성공
480  번째 접속성공
481  번째 접속성공
482  번째 접속성공
483  번째 접속성공
484  번째 접속성공
485  번째 접속성공
486  번째 접속성공
487  번째 접속성공
488  번째 접속성공
489  번째 접속성공
490  번째 접속성공
491  번째 접속성공
492  번째 접속성공
493  번째 접속성공
494  번째 접속성공
495  번째 접속성공
496  번째 접속성공
497  번째 접속성공
498  번째 접속성공
499  번째 접속성공
500  번째 접속성공
501  번째 접속성공
502  번째 접속성공
503  번째 접속성공
504  번째 접속성공
505  번째 접속성공
506  번째 접속성공
507  번째 접속성공
508  번째 접속성공
509  번째 접속성공
510  번째 접속성공
511  번째 접속성공
512  번째 접속성공
513  번째 접속성공
514  번째 접속성공
515  번째 접속성공
516  번째 접속성공
517  번째 접속성공
518  번째 접속성공
519  번째 접속성공
520  번째 접속성공
521  번째 접속성공
522  번째 접속성공
523  번째 접속성공
524  번째 접속성공
525  번째 접속성공
526  번째 접속성공
527  번째 접속성공
528  번째 접속성공
529  번째 접속성공
530  번째 접속성공
531  번째 접속성공
532  번째 접속성공
533  번째 접속성공
534  번째 접속성공
535  번째 접속성공
536  번째 접속성공
537  번째 접속성공
538  번째 접속성공
539  번째 접속성공
540  번째 접속성공
541  번째 접속성공
542  번째 접속성공
543  번째 접속성공
544  번째 접속성공
545  번째 접속성공
546  번째 접속성공
547  번째 접속성공
548  번째 접속성공
549  번째 접속성공
550  번째 접속성공
551  번째 접속성공
552  번째 접속성공
553  번째 접속성공
554  번째 접속성공
555  번째 접속성공
556  번째 접속성공
557  번째 접속성공
558  번째 접속성공
559  번째 접속성공
560  번째 접속성공
561  번째 접속성공
562  번째 접속성공
563  번째 접속성공
564  번째 접속성공
565  번째 접속성공
566  번째 접속성공
567  번째 접속성공
568  번째 접속성공
569  번째 접속성공
570  번째 접속성공
571  번째 접속성공
572  번째 접속성공
573  번째 접속성공
574  번째 접속성공
575  번째 접속성공
576  번째 접속성공
577  번째 접속성공
578  번째 접속성공
579  번째 접속성공
580  번째 접속성공
581  번째 접속성공
582  번째 접속성공
583  번째 접속성공
584  번째 접속성공
585  번째 접속성공
586  번째 접속성공
587  번째 접속성공
588  번째 접속성공
589  번째 접속성공
590  번째 접속성공
591  번째 접속성공
592  번째 접속성공
593  번째 접속성공
594  번째 접속성공
595  번째 접속성공
596  번째 접속성공
597  번째 접속성공
598  번째 접속성공
599  번째 접속성공
600  번째 접속성공
601  번째 접속성공
602  번째 접속성공
603  번째 접속성공
604  번째 접속성공
605  번째 접속성공
606  번째 접속성공
607  번째 접속성공
608  번째 접속성공
609  번째 접속성공
610  번째 접속성공
611  번째 접속성공
612  번째 접속성공
613  번째 접속성공
614  번째 접속성공
615  번째 접속성공
616  번째 접속성공
617  번째 접속성공
618  번째 접속성공
619  번째 접속성공
620  번째 접속성공
621  번째 접속성공
622  번째 접속성공
623  번째 접속성공
624  번째 접속성공
625  번째 접속성공
626  번째 접속성공
627  번째 접속성공
628  번째 접속성공
629  번째 접속성공
630  번째 접속성공
631  번째 접속성공
632  번째 접속성공
633  번째 접속성공
634  번째 접속성공
635  번째 접속성공
636  번째 접속성공
637  번째 접속성공
638  번째 접속성공

639  번째 접속성공
640  번째 접속성공
641  번째 접속성공
642  번째 접속성공
643  번째 접속성공
644  번째 접속성공
645  번째 접속성공
646  번째 접속성공
647  번째 접속성공
648  번째 접속성공
649  번째 접속성공
650  번째 접속성공
651  번째 접속성공
652  번째 접속성공
653  번째 접속성공
654  번째 접속성공
655  번째 접속성공
656  번째 접속성공
657  번째 접속성공
658  번째 접속성공
659  번째 접속성공
660  번째 접속성공
661  번째 접속성공
662  번째 접속성공
663  번째 접속성공

In [167]:
kospi

            date    price  delta   volume
0     2021.02.04  3087.55 -42.13  1460945
1     2021.02.03  3129.68  32.87   901788
2     2021.02.02  3096.81  40.28   887313
3     2021.02.01  3056.53  80.32   969262
4     2021.01.29  2976.21 -92.84   995071
...          ...      ...    ...      ...
3972  2005.01.13   885.54   5.51   290672
3973  2005.01.12   880.03  -4.26   321629
3974  2005.01.11   884.29  10.11   364432
3975  2005.01.10   874.18   3.34   275961
3976  2005.01.07   870.84  -0.44   294803

[3977 rows x 4 columns]